### ISSUE TITLE
How the sports are choosen ?

### ISSUE THREAD

**Issue by tmos** [Spieldy/sport-max#3]
Hi,

I would like to discuss with the community about how the featured sports are choosen ? I think that it looks like a decision taken without consulting anyone, and I'm not sure how much it fits with the inherent nature of the open source licence of the project.

Please, let's vote for the sports featured in our dear sport-max.

Regards,
Tom

**Comment by quentin-sommer** [comment]
I think we should fork this project to allow more sports into it if the steering here isn't friendly.

**Comment by tmos** [comment]
Let's give the creators a chance to add some high-testo sports, otherwise, le'ts fork it into `sport-ultra-max`!
